openapi: 3.0.3
info:
  version: 1.0.0
  title: Station Registry Example
  description: Simple station registry example service. __For demo & testing purposes__.
tags:
- name: stations
paths:
  /stations:
    get:
      operationId: app.get_station_list
      tags:
      - stations
      description: Return a list of stations
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
  /stations/{station_id}:
    get:
      operationId: app.get_station
      tags:
      - stations
      description: Return information about one station
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
        404:
          description: Station not found
      parameters:
      - $ref: '#/components/parameters/station_id'
components:
  parameters:
    station_id:
      name: station_id
      in: path
      description: Unique identifier for the station
      required: true
      schema:
        type: string
        example: SK1900
  schemas:
    Station:
      type: object
      properties:
        id:
          type: string
          example: SK1000
        name:
          type: string
          example: N KOSTERFJORDEN 1
        coordinates:
          type: object
          properties:
            latitude:
              type: number
              format: float
              example: 58.90209
            longitude:
              type: number
              format: float
              example: 11.08653
