openapi: 3.0.3
info:
  version: 1.0.0
  title: SVAR Area Example
  description: Get water body definitions for a given position.
tags:
- name: water_bodies
paths:
  /positions:
    get:
      operationId: app.get_info
      tags:
      - water_bodies
      description: Return a geojson of one water_body
      parameters:
        - $ref: '#/components/parameters/latitude'
        - $ref: '#/components/parameters/longitude'
        - $ref: '#/components/parameters/attribute'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WaterBody'
        404:
          description: Position not found
components:
  schemas:
    WaterBody:
      type: object
  parameters:
    latitude:
      in: query
      name: latitude
      schema:
        type: string
    longitude:
      in: query
      name: longitude
      schema:
        type: string
    attribute:
      in: query
      name: attribute
      schema:
        type: string
