openapi: 3.0.3
info:
  version: 1.0.0
  title: SVAR Area Example
  description: Get water body definitions for a given position.
tags:
- name: water_bodies
paths:
  /positions:
    get:
      operationId: app.get_area_example
      tags:
      - water_bodies
      description: Return a geojson of one water_body
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WaterBody'
  /positions/{latitude}&{longitude}&{key}:
    post:
      operationId: app.get_water_body
      tags:
      - water_bodies
      description: Returns information about one water body for which the given position lies within.
      parameters:
        - in: path
          name: latitude
          schema:
            type: string
            properties:
              latitude:
                type: string
        - in: path
          name: longitude
          schema:
            type: string
            properties:
              longitude:
                type: string
        - in: path
          name: key
          schema:
            type: string
            properties:
              key:
                type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/WaterBody'
        404:
          description: Position not found

components:
  schemas:
    WaterBody:
      type: object
